# External host address of this server
ExternalHost = "127.0.0.1"

# List of supported games
Games = [
  "SPLINTERCELL3PCADVERS",
  "SPLINTERCELL3PCCOOP",
  "SPLINTERCELL3PS2US",
  "SPLINTERCELL3PC",
  "HEROES_5"
]

[Web]
Host = "0.0.0.0"
Port = 80

[Router]
Host = "0.0.0.0"
Port = 40000

[NAT]
Port = 7781

[CDKey]
Port = 44000