package router

const (
	ERRORROUTER_UNKNOWNERROR            = 0
	ERRORROUTER_NOTREGISTERED           = 1
	ERRORROUTER_PASSWORDNOTCORRECT      = 2
	ERRORROUTER_NOTDISCONNECTED         = 3
	ERRORROUTER_ARENANOTAVAILABLE       = 4
	ERRORROUTER_FRIENDSNOTAVAILABLE     = 5
	ERRORROUTER_NAMEALREADYUSED         = 6
	ERRORROUTER_PLAYERNOTCONNECTED      = 7
	ERRORROUTER_PLAYERNOTREGISTERED     = 8
	ERRORROUTER_PLAYERCONNECTED         = 9
	ERRORROUTER_PLAYERALREADYREGISTERED = 10
	ERRORROUTER_CLIENTVERSIONTOOOLD     = 11
	ERRORROUTER_DBINBACKUPMODE          = 12
	ERRORROUTER_DBPROBLEM               = 13
	ERRORROUTER_CLIENTINCOMPATIBLE      = 50
)

const (
	ERRORSECURE_USERNAMEEXISTS    = 1
	ERRORSECURE_USERNAMEMALFORMED = 2
	ERRORSECURE_USERNAMEFORBIDDEN = 3
	ERRORSECURE_INVALIDACCOUNT    = 4
	ERRORSECURE_USERNAMERESERVED  = 5
	ERRORSECURE_PASSWORDMALFORMED = 11
	ERRORSECURE_PASSWORDFORBIDDEN = 13
	ERRORSECURE_INVALIDPASSWORD   = 15
	ERRORSECURE_DATABASEFAILED    = 100
	ERRORSECURE_BANNEDACCOUNT     = 501
	ERRORSECURE_BLOCKEDACCOUNT    = 502
	ERRORSECURE_LOCKEDACCOUNT     = 512
)
