package router

// Errors returned by the login service
const (
	ERRORROUTER_UNKNOWNERROR            = 0
	ERRORROUTER_NOTREGISTERED           = 1
	ERRORROUTER_PASSWORDNOTCORRECT      = 2
	ERRORROUTER_NOTDISCONNECTED         = 3
	ERRORROUTER_ARENANOTAVAILABLE       = 4
	ERRORROUTER_FRIENDSNOTAVAILABLE     = 5
	ERRORROUTER_NAMEALREADYUSED         = 6
	ERRORROUTER_PLAYERNOTCONNECTED      = 7
	ERRORROUTER_PLAYERNOTREGISTERED     = 8
	ERRORROUTER_PLAYERCONNECTED         = 9
	ERRORROUTER_PLAYERALREADYREGISTERED = 10
	ERRORROUTER_CLIENTVERSIONTOOOLD     = 11
	ERRORROUTER_DBINBACKUPMODE          = 12
	ERRORROUTER_DBPROBLEM               = 13
	ERRORROUTER_CLIENTINCOMPATIBLE      = 50
)

// Errors returned by the friends service
const (
	ERRORFRIENDS_FRIENDNOTEXIST         = 14
	ERRORFRIENDS_NOTINARENA             = 15
	ERRORFRIENDS_PLAYERNOTONLINE        = 16
	ERRORFRIENDS_NOTINSESSION           = 17
	ERRORFRIENDS_PLAYERIGNORE           = 18
	ERRORFRIENDS_ALREADYCONNECTED       = 19
	ERRORFRIENDS_NOMOREPLAYERS          = 20
	ERRORFRIENDS_NOPLAYERSCORE          = 47
	ERRORFRIENDS_SEARCHPLAYERFINISHED   = 48
	ERRORFRIENDS_PLAYERSTATUSCOREONLINE = 56
)

// Errors for Secure Accounts
const (
	ERRORSECURE_USERNAMEEXISTS    = 1
	ERRORSECURE_USERNAMEMALFORMED = 2
	ERRORSECURE_USERNAMEFORBIDDEN = 3
	ERRORSECURE_INVALIDACCOUNT    = 4
	ERRORSECURE_USERNAMERESERVED  = 5
	ERRORSECURE_PASSWORDMALFORMED = 11
	ERRORSECURE_PASSWORDFORBIDDEN = 13
	ERRORSECURE_INVALIDPASSWORD   = 15
	ERRORSECURE_DATABASEFAILED    = 100
	ERRORSECURE_BANNEDACCOUNT     = 501
	ERRORSECURE_BLOCKEDACCOUNT    = 502
	ERRORSECURE_LOCKEDACCOUNT     = 512
)

// Errors returned by the session service
const (
	ERRORARENA_SESSIONEXIST             = 21
	ERRORARENA_GAMENOTALLOWED           = 22
	ERRORARENA_NUMBERPLAYER             = 23
	ERRORARENA_NUMBERSPECTATOR          = 24
	ERRORARENA_VISITORNOTALLOWED        = 25
	ERRORARENA_NOTREGISTERED            = 26
	ERRORARENA_NOMOREPLAYERS            = 27
	ERRORARENA_NOMORESPECTATORS         = 28
	ERRORARENA_PLAYERNOTREGISTERED      = 29
	ERRORARENA_SESSIONNOTAVAILABLE      = 30
	ERRORARENA_SESSIONINPROCESS         = 31
	ERRORARENA_BADGAMEVERSION           = 32
	ERRORARENA_PASSWORDNOTCORRECT       = 33
	ERRORARENA_ALREADYINSESSION         = 34
	ERRORARENA_NOTMASTER                = 35
	ERRORARENA_NOTINSESSION             = 36
	ERRORARENA_MINPLAYERS               = 37
	ERRORARENA_ADMINGAMEDOESNOTEXIST    = 38
	ERRORARENA_ADMINSESSIONDOESNOTEXIST = 39
	ERRORARENA_CONNECTADDCONNECTION     = 40
	ERRORARENA_CONNECTSENDLOGINMSG      = 41
	ERRORARENA_ERRORLOGINMESSAGE        = 42
	ERRORARENA_NOHOSTARENA              = 43
	ERRORARENA_ARENADISCONNECTED        = 44
	ERRORARENA_INVALIDGROUPNAME         = 45
	ERRORARENA_INVALIDGAMETYPE          = 46
	ERRORARENA_NOMOREGAMEMODULE         = 47
	ERRORARENA_PASSPORTLABELNOTFOUND    = 48
	ERRORARENA_PASSPORTFAIL             = 49
	ERRORARENA_CREATENOTALLOWED         = 50
	ERRORARENA_INVALIDSESSIONTYPE       = 51
	ERRORARENA_SESSIONCLOSE             = 52
	ERRORARENA_NOTCREATOR               = 53
	ERRORARENA_DEDICATEDSERVERONLY      = 54
)
