package cdkey

const (
	CDKM_E_PLAYER_UNKNOWN = 0
	CDKM_E_PLAYER_INVALID = 1
	CDKM_E_PLAYER_VALID   = 2
)

const (
	CDKM_CHALLENGE       = 1
	CDKM_ACTIVATION      = 2
	CDKM_AUTH            = 3
	CDKM_VALIDATION      = 4
	CDKM_PLAYER_STATUS   = 5
	CDKM_DISCONNECT_USER = 6
	CDKM_STILL_ALIVE     = 7
)
